# Generated by Django 4.0.3 on 2022-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalentries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_title',
            field=models.TextField(default='empty title'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.TextField(default='empty date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(default='empty text'),
        ),
    ]
